name: qr_generator
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.2+2
environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  qr_flutter: ^4.1.0
  flutter_otp_text_field: ^1.1.1
  share: ^2.0.4
  path_provider: ^2.1.0
  screenshot: ^2.1.0
  onesignal_flutter: ^5.0.1
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  firebase_messaging: ^14.6.7
  easy_splash_screen: ^1.0.4
  lottie: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/