// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEb3F1lf5zINtt00jB4Qc7Y4jIdzCUIiQ',
    appId: '1:1054856280872:web:57821822fc791c065e6e1d',
    messagingSenderId: '1054856280872',
    projectId: 'qr-generator-9ec11',
    authDomain: 'qr-generator-9ec11.firebaseapp.com',
    storageBucket: 'qr-generator-9ec11.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYL2BHZi5Vr8Ew7pE9cJyUI2TRBSSZl4',
    appId: '1:1054856280872:android:d19f677bb6c0268e5e6e1d',
    messagingSenderId: '1054856280872',
    projectId: 'qr-generator-9ec11',
    storageBucket: 'qr-generator-9ec11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZ1hPKWdPTCTlN_QkjY-64D6J55OauNo',
    appId: '1:1054856280872:ios:cda03a981096a5d55e6e1d',
    messagingSenderId: '1054856280872',
    projectId: 'qr-generator-9ec11',
    storageBucket: 'qr-generator-9ec11.appspot.com',
    iosClientId: '1054856280872-ou2la6pgtc24q7rq63kg9gpugqsqgflt.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrGenerator.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVZ1hPKWdPTCTlN_QkjY-64D6J55OauNo',
    appId: '1:1054856280872:ios:cda03a981096a5d55e6e1d',
    messagingSenderId: '1054856280872',
    projectId: 'qr-generator-9ec11',
    storageBucket: 'qr-generator-9ec11.appspot.com',
    iosClientId: '1054856280872-ou2la6pgtc24q7rq63kg9gpugqsqgflt.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrGenerator.RunnerTests',
  );
}
